version: '3'

services:
  livcam_publisher:
    build:
      context: .
    command:
      - /ros2_ws/start_living_publisher.sh
    devices:
      - "/dev/video0:/dev/video0"
    restart: always
    networks:
      - docker_net

  livcam_subscriber_save:
    build:
      context: .
    command:
      - /ros2_ws/start_living_subscriber_save.sh
    volumes:
      - /mnt/usbdisk1/CAM_DATA/living_cam_data:/ros2_ws/living_cam_data
    restart: always
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge
    ipam:
      driver: default
